export const PaymentInfoList = [
    {
        logo: 'assets/img/subscription/core_logo.png',
        isChecked: false,
        isMostPopular: false,
        yearCost: 0,
        monthCost: 0,
        yearPrice: 0,
        monthPrice: 0,
        yearCostText: '$0',
        monthCostText: '$0',
        setupCost: 'Free for 3 Months',
        setupText: '',
        info: 'For small teams starting with digital transformation.',
        buttonText: 'Explore Dadyin Core',
        keyFeatureTitle: 'Key features of Dadyin Core',
        keyFeatureList: ['DadyIn Quick checkout fees 7%', 'Transactions limit : 12/month', 'Container management : 2/year'],
        quickCheckoutFees: 7.0,
        allowedTransactionsByMonth: 12,
        containerManagementByYear: 2,
        productSupport: 0,
        productSupportValue:0,
        allowedNoOfBranches: 0,
        businessSubscriptionId: 1,
        subscriptionPackageMonthAmount: 0,
        subscriptionPackageYearAmount: 0,
        setupCostValue: 0
    },
    {
        logo: 'assets/img/subscription/edge_logo.png',
        isChecked: false,
        isMostPopular: false,
        yearCost: 31999,
        monthCost: 29299,
        yearPrice: 31999,
        monthPrice: 29299,
        yearCostText: '$2,999',
        monthCostText: '$299',
        setupCost: '+ $29,000',
        setupText: '(one time fees)',
        info: 'For growing teams expand into import and export with smoother operations.',
        buttonText: 'Get Dadyin Edge',
        keyFeatureTitle: 'Key features of Dadyin Edge',
        keyFeatureList: ['DadyIn Quick checkout fees 5%', 'Transactions limit : 200/month', 'Container management : 12/year', 'CRM access provided', 'Product adding support : for 1 month'],
        quickCheckoutFees: 5.0,
        allowedTransactionsByMonth: 200,
        containerManagementByYear: 12,
        productSupport: '1M',
        productSupportValue:1,
        allowedNoOfBranches: 0,
        businessSubscriptionId: 2,
        subscriptionPackageMonthAmount: 299.0,
        subscriptionPackageYearAmount: 2999.0,
        setupCostValue: 29000.0
    },
    {
        logo: 'assets/img/subscription/elite_logo.png',
        isChecked: true,
        isMostPopular: true,
        yearCost: 33999,
        monthCost: 29499,
        yearPrice: 33999,
        monthPrice: 29499,
        yearCostText: '$4,999',
        monthCostText: '$499',
        setupCost: '+ $29,000',
        setupText: '(one time fees)',
        info: 'For established businesses running at scale with international operations.',
        buttonText: 'Get Dadyin Eite',
        keyFeatureTitle: 'Key features of Dadyin Elite',
        keyFeatureList: ['DadyIn Quick checkout fees 3%', 'Transactions limit : 500/month', 'Container management : 50/year', 'Branches permitted : 01', 'CRM access provided', 'Product adding support : for 2 month'],
        quickCheckoutFees: 3.0,
        allowedTransactionsByMonth: 500,
        containerManagementByYear: 50,
        productSupport: '2M',
        productSupportValue:2,
        allowedNoOfBranches: 1,
        businessSubscriptionId: 3,
        subscriptionPackageMonthAmount: 499.0,
        subscriptionPackageYearAmount: 4999.0,
        setupCostValue: 29000.0
    },
    {
        logo: 'assets/img/subscription/empire_logo.png',
        isChecked: false,
        isMostPopular: false,
        yearCost: 38999,
        monthCost: 29999,
        yearPrice: 38999,
        monthPrice: 29999,
        yearCostText: '$9,999',
        monthCostText: '$999',
        setupCost: '+ $29,000',
        setupText: '(one time fees)',
        info: 'For global brands with complex operations, multi-country sourcing, and high-volume logistics.',
        buttonText: 'Get Dadyin Empire',
        keyFeatureTitle: 'Key features of Dadyin Empire',
        keyFeatureList: ['DadyIn Quick checkout fees 1%', 'Transactions limit : Unlimited', 'Container management : Unlimited', 'Branches permitted : 03', 'CRM access provided', 'Product adding support : for 3 month'],
        quickCheckoutFees: 1.0,
        allowedTransactionsByMonth: -1,
        containerManagementByYear: -1,
        productSupport: '3M',
        productSupportValue:3,
        allowedNoOfBranches: 3,
        businessSubscriptionId: 4,
        subscriptionPackageMonthAmount: 999.0,
        subscriptionPackageYearAmount: 9999.0,
        setupCostValue: 29000.0
    }
]