export const sidebarMenu = [
  {
    id: 1,
    label: 'Home',
    icon: 'Home',
    path: '/home',
    childs: [],
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  {
    id: 2,
    label: 'Customer',
    icon: 'Customers',
    path: '/home/customer/list?currentStepIndex=0',
    childs: [
      {
        id: 10,
        label: 'All',
        icon: 'Customers',
        path: '/home/customer/list?currentStepIndex=0',
        role: ['ADMIN', 'STAFF', 'CRM', 'MANAGER'],
      },
      {
        id: 11,
        label: 'Customers',
        icon: 'Customers',
        path: '/home/customer/list?currentStepIndex=1',
        role: ['ADMIN', 'STAFF', 'CRM', 'MANAGER'],
      },
      {
        id: 12,
        label: 'Leads',
        icon: 'Customers',
        path: '/home/lead/list?currentStepIndex=2',
        role: ['ADMIN', 'STAFF', 'CRM', 'MANAGER'],
      },
      {
        id: 13,
        label: 'Prospects',
        icon: 'Customers',
        path: '/home/prospect/list?currentStepIndex=3',
        role: ['ADMIN', 'STAFF', 'CRM', 'MANAGER'],
      },
    ],
    role: ['ADMIN', 'STAFF', 'CRM', 'MANAGER'],
  },
  {
    id: 3,
    label: 'Vendor',
    icon: 'Vendor',
    path: '/home/vendor/list',
    childs: [
      {
        id: 1,
        label: 'Vendor',
        icon: 'Vendor',
        path: '/home/vendor/list',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  {
    id: 4,
    label: 'Products management',
    icon: 'Product',
    path: '/home/product-management',
    childs: [
      {
        id: 1,
        label: 'Products Type',
        icon: 'Product',
        path: '/home/product-management/product-type',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
      {
        id: 2,
        label: 'Products Templates',
        icon: 'Product',
        path: '/home/product-management/product-template',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
      {
        id: 3,
        label: 'Products ',
        icon: 'Product',
        path: '/home/product-management/product',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  {
    id: 5,
    label: 'Orders management',
    icon: 'Order management',
    path: '/home/order-management',
    childs: [
      {
        id: 1,
        label: 'Customer',
        icon: 'Order management',
        path: '/home/order-management/customer',
        role: ['ADMIN', 'STAFF', 'MANAGER', 'CRM'],
      },
      {
        id: 2,
        label: 'Vendor',
        icon: 'Order management',
        path: '/home/order-management/vendor',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
    role: ['ADMIN', 'STAFF', 'MANAGER', 'CRM'],
  },
  {
    id: 6,
    label: 'Quick Checkout',
    icon: 'Quick checkout',
    path: '/home/quick-checkout',
    childs: [],
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  {
    id: 7,
    label: 'Container management',
    icon: 'Container',
    path: '/home/container-management',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
    childs: [
      {
        id: 1,
        label: 'Import Container',
        icon: 'Container',
        path: '/home/container-management/container/import',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
      {
        id: 2,
        label: 'Export Container',
        icon: 'Container',
        path: '/home/container-management/container/export',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
  },
  {
    id: 9,
    label: 'Inventory management',
    icon: 'Inventory',
    path: '/home/inventory-management',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
    childs: [
      {
        id: 1,
        label: 'Inventory In',
        icon: 'Inventory',
        path: '/home/inventory-management/inventoryin',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
      {
        id: 2,
        label: 'Inventory Out',
        icon: 'Inventory',
        path: '/home/inventory-management/inventoryout',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
  },
  {
    id: 8,
    label: 'System Config',
    icon: 'System config',
    path: '/home/system-config',
    childs: [
      {
        id: 1,
        label: 'Order management',
        icon: 'System config',
        path: '/home/system-config/order-management',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
      {
        id: 1,
        label: 'User management',
        icon: 'System config',
        path: '/home/system-config/user-management',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
      {
        id: 1,
        label: 'Category management',
        icon: 'System config',
        path: '/home/system-config/category-management',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  {
    id: 9,
    label: 'Payment management',
    icon: 'Payments',
    path: '/home/payment-management',
    childs: [
      {
        id: 2,
        label: 'Receivable',
        icon: 'Payments',
        path: '/home/payment-management',
        role: ['ADMIN', 'STAFF', 'MANAGER'],
      },
    ],
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
];

export const topList = [
  // {
  //     id: 1,
  //     label: 'My Tasks',
  //     icon: 'description',
  //     path: '/home',
  // },
  // {
  //     id: 2,
  //     label: 'Messages',
  //     icon: 'description',
  //     path: '/home',
  // },
  {
    id: 3,
    label: 'Product#',
    icon: 'Product',
    path: '/home/product-management/product',
    countKey: 'Products',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },

  // {
  //     id: 4,
  //     label: 'Vendors',
  //     icon: 'description',
  //     path: '/home/vendor/list',
  // },
  // {
  //     id: 5,
  //     label: 'Customers',
  //     icon: 'description',
  //     path: '/home/customer/list',
  // },
  {
    id: 6,
    label: 'Quick checkout#',
    icon: 'Quick checkout',
    path: '/home/quick-checkout',
    countKey: 'QuickCheckoutOrders',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  // {
  //     id: 8,
  //     label: 'Sales Rep.',
  //     icon: 'description',
  //     path: '/home',
  // },
  // {
  //     id: 9,
  //     label: 'Drivers',
  //     icon: 'description',
  //     path: '/home',
  // }
];

export const vendorList = [
  {
    id: 1,
    label: 'RFQ',
    icon: 'description',
    viewpath: '/home/order-management/vendor?currentStepIndex=0',
    addpath: '/home/order-management/vendor/rfq/add',
    isActive: true,
    key: 'RFQ',
    countKey: 'RFQ',
  },
  {
    id: 2,
    label: 'Rec. Quote',
    icon: 'description',
    viewpath: '/home/order-management/vendor?currentStepIndex=1',
    addpath: '',
    isActive: true,
    key: 'ReceivedQuotation',
    countKey: 'ReceivedQuotation',
  },
  {
    id: 3,
    label: 'Purchase Order',
    icon: 'Order management',
    viewpath: '/home/order-management/vendor?currentStepIndex=2',
    addpath: '/home/order-management/vendor/purchaseorder/add',
    isActive: true,
    key: 'PurchaseOrder',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
    countKey: 'PurchaseOrder',
  },
  {
    id: 4,
    label: 'Bill',
    icon: 'description',
    viewpath: '/home/order-management/vendor?currentStepIndex=3',
    addpath: '/home/order-management/vendor/bill/add',
    isActive: true,
    key: 'Bill',
    countKey: 'Bill',
  }
  // ,
  // {
  //   id: 4,
  //   label: 'Quick checkout',
  //   icon: 'description',
  //   viewpath: '/home/quick-checkout',
  //   addpath: '/home/quick-checkout/order',
  //   isActive: true,
  //   key: 'QuickCheckout',
  //   countKey: 'QuickCheckout',
  // },
  // {
  //     id: 5,
  //     label: 'Rec. SO',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  // {
  //     id: 6,
  //     label: 'PO Fulfillment',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  // {
  //     id: 7,
  //     label: 'Bills',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  // {
  //     id: 8,
  //     label: 'Returns',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  // {
  //     id: 9,
  //     label: 'Vendor Credit',
  //     icon: 'description',
  //     path: '/home',
  //     isActive: false,
  //     key: null
  // },

  // {
  //     id: 10,
  //     label: 'Drivers',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // }
];

export const customerList = [
  {
    id: 1,
    label: 'Rec. RFQ',
    icon: 'description',
    viewpath: '/home/order-management/customer?currentStepIndex=0',
    addpath: '/home/order-management/customer/receivedRfq/add',
    isActive: true,
    key: 'ReceivedEnquiry',
    countKey: 'ReceivedEnquiry',
  },
  {
    id: 2,
    label: 'Quotation',
    icon: 'description',
    viewpath: '/home/order-management/customer?currentStepIndex=1',
    addpath: '/home/order-management/customer/quotation/add',
    isActive: true,
    key: 'Quotation',
    countKey: 'Quotation',
  },
  {
    id: 3,
    label: 'Rec. PO',
    icon: 'Order management',
    viewpath: '/home/order-management/customer?currentStepIndex=2',
    addpath: '/home/order-management/customer/receivedPo/add',
    isActive: true,
    key: 'ReceivedPurchaseOrder',
    countKey: 'ReceivedPurchaseOrder',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
  },
  // {
  //     id: 4,
  //     label: 'Sales Order',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  // {
  //     id: 5,
  //     label: 'SO Fulfillment',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  {
    id: 3,
    label: 'Invoice',
    icon: 'Order management',
    viewpath: '/home/order-management/customer?currentStepIndex=3',
    addpath: '/home/order-management/customer/invoice/add',
    isActive: true,
    key: 'Invoice',
    role: ['ADMIN', 'STAFF', 'MANAGER'],
    countKey: 'Invoice',
  },
  // {
  //     id: 7,
  //     label: 'Rec. Returns',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // },
  // {
  //     id: 8,
  //     label: 'Credit Memo',
  //     icon: 'description',
  //     viewpath: '',
  //     addpath: '',
  //     isActive: false,
  //     key: null
  // }
];
