export const WEIGHT_ATTRIBUTE_VALUE_FOR_RAW_MATERIAL = 1;
export const WEIGHT_ATTRIBUTE_UOM_FOR_RAW_MATERIAL = 'mt';
export const COST_ATTRIBUTE_UOM_FOR_RAW_MATERIAL = 'USD';
export const DENSITY_ATTRIBUTE_UOM_FOR_RAW_MATERIAL = 'gm/cm3';
