import { CALCULATED_COST_ID, CONVERSION_COST_ID, COST_ID, COST_PER_METRICTON_ID, DENSITY_ID, MATERIAL_COST_ID, WEIGHT_ID } from "../../common/attribute-identifiers";

export const PRODUCT_OF_PROCESS_ATTRIBUTES = [
    WEIGHT_ID,
    COST_ID,
    DENSITY_ID,
    COST_PER_METRICTON_ID,
    MATERIAL_COST_ID,
    CONVERSION_COST_ID,
    CALCULATED_COST_ID
]