import { Injectable } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms';

@Injectable({
  providedIn: 'root',
})
export class QuickCheckoutFormsService {
  constructor(public _fb: FormBuilder) {}

  createPOForm(): FormGroup {
    return this._fb.group({
      deliveryCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: null,
      }),
      isReceiving: [false],
      id: [null],
      contactId: [null],
      debugInformation: [null],
      deliveryAddress: this._fb.group({
        addressLine: [null],
        addressCountry: [null],
        addressState: [null],
        addressCity: [null],
        addressZipCode: [null],
      }),
      paymentEnabled: [false],
      status: ['DRAFT'],
      buyingType: ['SKU'],
      saleOrderId: [null],
      saleOrderStatus: [null],
      saleOrderFromId: [null],
      saleOrderToId: [null],
      isQuickCheckout: [true],
      saleOrderTransactionId: [null],
      transactionId: [null],
      requestFrom: this._fb.group({
        id: [null],
        debugInformation: null,
        businessLines: [null],
        relationAccounts: [null],
        branchDetails: null,
        code: null,
        externalId: null,
        businessLogo: null,
        companyStamp: null,
        digitalStamp: null,
        isSystemAccount: null,
        type: null,
        roleName: null,
        fromInvite: false,
        inviteId: null,
        name: [null],
        firstName: [null],
        lastName: [null],
        language: [null],
        currency: [null],
        currency2nd: [null],
        gst: [null],
        primaryContact: [null],
        hibernateLazyInitializer: [],
      }),
      requestTo: this._fb.group({
        id: [1],
        debugInformation: null,
        businessLines: [null],
        relationAccounts: [null],
        branchDetails: null,
        code: null,
        externalId: null,
        businessLogo: null,
        companyStamp: null,
        digitalStamp: null,
        isSystemAccount: null,
        type: null,
        roleName: null,
        fromInvite: false,
        inviteId: null,
        name: [null],
        firstName: [null],
        lastName: [null],
        language: [null],
        currency: [null],
        currency2nd: [null],
        gst: [null],
        primaryContact: [null],
        hibernateLazyInitializer: [],
      }),
      requiredByDate: [null],
      returnDate: [null],
      importLocalType: ['LOCAL'],
      deliveryPickup: ['DELIVERY'],
      reminderCount: [null],
      odometer: this._fb.group({
        value: [null],
        odometerType: [null],
      }),
      incoTermId: [null],
      departurePortId: [null],
      arrivalPortId: [null],
      portDescription: [null],
      containerTypeId: [null],
      dadyInPoints: [],
      containerTypeDescription: [null],
      noteId: [null],
      noteDescription: [null],
      isRead: [false],
      cost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      weight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      volume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      audit: [],
      buddyAccounts: [],
      productPackages: this._fb.array([]),
      paymentTermDescription: [null],
      editTillDate: [null],
      expectedByDate: [null],
      date: [null],
      shipper: [null],
      quantity: [null],
      discount: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      salesTax: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      rfQuotationId: [null],
      contactName: [null],
      contactPhone: [null],
      palletTypeInformation: [null],
      paymentStatus: [null],
      paymentTermId: [null],
      referenceOrder: [null],
    });
  }

  productPackageForm(): FormGroup {
    return this._fb.group({
      id: [null],
      audit: [null],
      deliveryDays: [null],
      isCustomized: [null],
      isNoGenericPurchase: [null],
      auditBusinessAccountName: [null],
      quantity: [null],
      skuQuantities: [null],
      skuWeight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      skuVolume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),

      unitQuantities: [null],
      unitCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      unitWeight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      unitVolume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      cost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      weight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalWeight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      volume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalVolume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      metricCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      productDetails: this._fb.group({
        id: [null],
        audit: [null],
        debugInformation: [null],
        isNoGenericPurchase: [null],
        preferredCustomerId: [null],
        isCustomized: [null],
        tierPricingDetail: [null],
        cost: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        weight: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        density: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        volume: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        surfaceArea: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        metricCost: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuCost: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuWeight: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuVolume: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuMetricCost: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        palletTypeInformation: [null],
        productMetaId: [null],
        skuPackageId: [null],
        productCode: [null],
        description: [null],
        exportDescription: [null],
        upcCode: [null],
        eanCode: [null],
        rating: [null],
        isCustomizable: [null],
        isSaleable: [null],
        isFavourite: [null],
        isRawMaterial: [null],
        isSupplies: [null],
        isPackagingMaterial: [null],
        isProductOfProcess: [null],
        numberOfItems: [null],
        numberOfProducts: [null],
        numberInPallet: [null],
        skuPackageContent: [null],
        qoh: [null],
        productTypeId: [null],
        productSubTypeId: [null],
        productTemplateId: [null],
        productTemplateName: [null],
        productTemplateCode: [null],
        productTypeDescription: [null],
        productSubTypeDescription: [null],
        productTemplateDescription: [null],
        productMetaBusinessAccountId: [null],
        productBusinessAccountId: [null],
        skuPackageType: [null],
        odometer: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuOdometer: [null],
        productImageFileName: [null],
        productImageFileNames: [null],
        skuFirstMinimumQuantity: [null],
        skuFirstMaximumQuantity: [null],
        skuFirstSkuType: [null],
        skuSecondMinimumQuantity: [null],
        skuSecondMaximumQuantity: [null],
        skuSecondSkuType: [null],
        skuThirdMinimumQuantity: [null],
        skuThirdMaximumQuantity: [null],
        skuThirdSkuType: [null],
        palletSkuType: [null],
        palletMqo: [null],
        truckSkuType: [null],
        truckMqo: [null],
        containerSkuType: [null],
        containerMqo: [null],
        skuFirstTier: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuSecondTier: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        skuThirdTier: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        palletTier: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        truckTier: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        containerTier: this._fb.group({
          attributeValue: [null],
          userConversionUom: [null],
        }),
        status: [null],
        isQuickCheckoutEligible: [null],
        isPalletAvailable: [null],
        unitName:[null]
      }),
      packageCustomAttributeValues: this._fb.array([]),
      sortOrder: [null],
      skuCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      productId: [null],
      packageId: [null],
      totalSKUs: [null],
      loadingType: ['FLOOR'],
      numberOfItems: [null],
      numberOfProducts: [null],
      numberInPallet: [null],
      unitName:[null]
    });
  }

  productPackageFormCalculate(): FormGroup {
    return this._fb.group({
      id: [null],
      isReceiving: [false],
      deliveryDays: [null],
      isCustomized: [null],
      isNoGenericPurchase: [null],
      quantity: [null],
      audit: [null],
      skuQuantities: [null],
      unitQuantities: [null],
      unitCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      unitWeight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      unitVolume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      cost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      weight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalWeight: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      volume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      totalVolume: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      metricCost: this._fb.group({
        attributeValue: [null],
        userConversionUom: [null],
      }),
      loadingType: ['FLOOR'],
      productDetails: [null],
      skuFirstMinimumQuantity: [null],
      skuFirstMaximumQuantity: [null],
      skuFirstSkuType: [null],
      skuSecondMinimumQuantity: [null],
      skuSecondMaximumQuantity: [null],
      skuSecondSkuType: [null],
      skuThirdMinimumQuantity: [null],
      skuThirdMaximumQuantity: [null],
      skuThirdSkuType: [null],
      packageCustomAttributeValues: this._fb.array([]),
      sortOrder: [null],
      skuCost: [null],
      productId: [null],
      packageId: [null],
      totalSKUs: [null],
      numberOfItems: [null],
      numberOfProducts: [null],
      numberInPallet: [null],
      unitName:[null]
    });
  }

  createCustomisationForm(): FormGroup {
    return this._fb.group({
      color: [null],
      upcCode: [null],
      printingColor: [null],
      side: [null],
      printContent: [null],
      orderDelivery: [null],
      logo: [null],
    });
  }
}
